---
- name: Crear usuario en Active Directory usando PowerShell
  hosts: all
  gather_facts: no
  vars:
    ad_username: "{{ ad_username }}"
    ad_password: "{{ ad_password }}"
    ad_logon_name: "{{ ad_logon_name }}"
    ad_groups: "{{ ad_groups | default([]) }}"  # opcional

  tasks:
    - name: Crear usuario en AD
      win_shell: |
        $Password = ConvertTo-SecureString "{{ ad_password }}" -AsPlainText -Force

        # Valor por defecto para descripción
        $Description = "Usuario creado desde AWX"

        # Valor por defecto para OU
        $OU = "OU=Usuarios,DC=mingrat,DC=lab"

        # Crear el usuario
        New-ADUser `
          -Name "{{ ad_username }}" `
          -SamAccountName "{{ ad_username }}" `
          -UserPrincipalName "{{ ad_logon_name }}" `
          -AccountPassword $Password `
          -Enabled $true `
          -Path $OU `
          -Description $Description `
          -ChangePasswordAtLogon $false `
          -PasswordNeverExpires $true
      register: new_user

    - name: Agregar usuario a grupos
      win_shell: |
        {% for group in ad_groups %}
        Add-ADGroupMember -Identity "{{ group }}" -Members "{{ ad_username }}"
        {% endfor %}
      when: ad_groups | length > 0

    - name: Mostrar resultado
      debug:
        var: new_user
